name: ML Pipeline CI/CD

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * 0'   # weekly retraining (Sunday)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

     
    # Checkout Code
     
    - name: Checkout code
      uses: actions/checkout@v3

     
    # Setup Python
     
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"

     
    # Upgrade pip
     
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

     
    # Install Dependencies
     
    - name: Install dependencies
      run: pip install -r requirements.txt

     
    # Run Tests (CI)
     
    - name: Run tests
      run: pytest

     
    # Train Model (MLflow)
     
    - name: Train Model
      run: python src/train.py

     
    # Deploy Model (CD)
     
    - name: Deploy Model
      if: success()
      run: python src/deploy.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}